services:
  mysql:
    image: mysql:8.0
    restart: no
    ports:
      - '3306:3306'
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring-boot-tutorial
    volumes:
      - spring-boot-tutorial-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  spring-boot-tutorial-data:
