spring:
  application:
    name: spring-boot-tutorial
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-tutorial
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

jwt:
  secret: super-duper-secret-key
  expiration: 86400

springdoc:
  swagger-ui:
    persist-authorization: true